#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP DIRECTORY
#=================================================
ynh_script_progression --message="Restoring the app directory..." --weight=2

ynh_restore_file --origin_path="$install_dir"

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Restoring data directory..." --weight=3

ynh_restore_file --origin_path="$data_dir"

#=================================================
# RESTORE DATABASE
#=================================================
ynh_script_progression --message="Restoring database..." --weight=5

ynh_restore_file --origin_path="database.db" --dest_path="$data_dir/prisma/dev.db"

#=================================================
# RESTORE NGINX CONFIGURATION
#=================================================
ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable "$app.service" --quiet
systemctl daemon-reload

#=================================================
# START DOCKER CONTAINER
#=================================================
ynh_script_progression --message="Starting Docker container..." --weight=5

cd "$install_dir"
docker-compose up -d

#=================================================
# START SERVICE
#=================================================
ynh_systemd_action --service_name="$app" --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Restoration completed for $app" --last
